service_name   = "preflight-curl-1"
owner_team     = "platform"
description    = "Preflight curl test from scaffolder API"
environment    = "dev"
aws_account_id = "123456789012"
cluster_name   = "eks-test-cluster"
gitlab_group   = "idp-group/devops/idp-platform"
