replicaCount: 1
image:
  repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/idp-poc/idp-devportal
  tag: "v1.0.0-84751ea3"
  pullPolicy: Always
service:
  type: NodePort
  port: 80
  nodePort: 31394
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
